#!/usr/bin/env python3
"""
Train historical user vectors from pre-generated preference files.

This script takes preference data generated by generate_historical_preferences.py
and trains LoRe user vectors for historical users.

Usage:
    python scripts/train_historical_users.py --preferences_file checkpoints/historical/preferences_historical_C013.json
    python scripts/train_historical_users.py --preferences_file ... --epochs 30 --learning_rate 1e-3
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import torch

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from apa.config import configure_environment, DatasetConfig
from apa.utils.embedding_utils import embed_texts, get_embedding_model
from apa.reward.lore_model import LoReRewardModel
from apa.historical.preference_gen import preferences_to_labels


def parse_args() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Train historical user vectors from preference files",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--preferences_file",
        type=str,
        required=True,
        help="Path to preferences JSON file (from generate_historical_preferences.py)",
    )
    parser.add_argument(
        "--lore_checkpoint",
        type=str,
        default=None,
        help="Path to trained LoRe model checkpoint",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=20,
        help="Number of epochs for training user vector",
    )
    parser.add_argument(
        "--learning_rate",
        type=float,
        default=1e-3,
        help="Learning rate for user vector training",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default=None,
        help="Output directory for checkpoints",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cuda" if torch.cuda.is_available() else "cpu",
        help="Device to train on",
    )
    return parser.parse_args()


def train_user_vector(
    V: torch.Tensor,
    embeddings_1: torch.Tensor,
    embeddings_2: torch.Tensor,
    labels: torch.Tensor,
    rank: int,
    epochs: int = 20,
    learning_rate: float = 1e-3,
    device: str = 'cpu',
) -> torch.Tensor:
    """
    Train a single user vector given frozen basis V.

    Args:
        V: Frozen basis matrix (embed_dim, rank)
        embeddings_1: Response 1 embeddings (n, embed_dim)
        embeddings_2: Response 2 embeddings (n, embed_dim)
        labels: Binary labels (n,) - 1 if response 2 preferred
        rank: Rank of the low-rank decomposition
        epochs: Number of training epochs
        learning_rate: Learning rate
        device: Device to train on

    Returns:
        Trained user vector (rank,)
    """
    w = torch.randn(rank, device=device) * 0.01
    w = w.clone().detach().requires_grad_(True)

    V = V.to(device)
    embeddings_1 = embeddings_1.to(device)
    embeddings_2 = embeddings_2.to(device)
    labels = labels.float().to(device)

    optimizer = torch.optim.Adam([w], lr=learning_rate)

    for epoch in range(epochs):
        optimizer.zero_grad()

        r1 = embeddings_1 @ V @ w
        r2 = embeddings_2 @ V @ w

        logits = r2 - r1

        loss = torch.nn.functional.binary_cross_entropy_with_logits(
            logits, labels, reduction='mean'
        )

        loss.backward()
        optimizer.step()

        if (epoch + 1) % 5 == 0:
            with torch.no_grad():
                preds = (logits > 0).float()
                acc = (preds == labels).float().mean()
                print(f"  Epoch {epoch + 1}/{epochs}: loss={loss.item():.4f}, acc={acc.item():.4f}")

    return w.detach().cpu()


def main() -> None:
    """Main entry point."""
    args = parse_args()

    configure_environment()
    dataset_config = DatasetConfig()

    # Load preferences file
    prefs_path = Path(args.preferences_file)
    if not prefs_path.exists():
        print(f"ERROR: Preferences file not found: {prefs_path}")
        print("Generate preferences first using: python scripts/generate_historical_preferences.py")
        sys.exit(1)

    print(f"Loading preferences from {prefs_path}")
    with open(prefs_path, 'r') as f:
        pref_data = json.load(f)

    century = pref_data['century']
    questions = pref_data['questions']
    preferences = pref_data['preferences']

    print(f"\n{'='*60}")
    print(f"Training Historical User Vector for {century}")
    print(f"{'='*60}\n")

    print(f"Preferences loaded:")
    print(f"  Century: {century}")
    print(f"  Questions: {len(questions)}")
    print(f"  Valid preferences: {pref_data.get('valid_count', 'N/A')}")
    print(f"  Avg consistency: {pref_data.get('avg_consistency', 'N/A'):.2%}" if isinstance(pref_data.get('avg_consistency'), (int, float)) else f"  Avg consistency: N/A")

    # Set up output directory
    output_dir = Path(args.output_dir) if args.output_dir else dataset_config.checkpoints_dir
    output_dir = output_dir / "historical"
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load LoRe model
    if args.lore_checkpoint:
        lore_path = Path(args.lore_checkpoint)
    else:
        lore_path = dataset_config.checkpoints_dir / "lore_K8_best.pt"

    if not lore_path.exists():
        print(f"ERROR: LoRe checkpoint not found at {lore_path}")
        print("Please train LoRe first using: python scripts/train_lore_prism.py")
        sys.exit(1)

    print(f"\nLoading LoRe model from {lore_path}")
    lore_model = LoReRewardModel.load(str(lore_path), device='cpu')
    V = lore_model.V.data.clone()
    rank = lore_model.rank
    embed_dim = lore_model.embed_dim

    print(f"LoRe model: embed_dim={embed_dim}, rank={rank}")

    # Convert preferences to labels
    labels = preferences_to_labels(preferences, as_binary=True)

    # Filter out invalid labels
    valid_mask = [l != -1 for l in labels]
    valid_indices = [i for i, v in enumerate(valid_mask) if v]
    labels = [labels[i] for i in valid_indices]
    valid_questions = [questions[i] for i in valid_indices]

    print(f"\nValid training samples: {len(labels)} / {len(preferences)}")

    if len(labels) == 0:
        print("ERROR: No valid preference labels found. Cannot train.")
        sys.exit(1)

    # Generate embeddings for the questions
    print("\nGenerating embeddings...")
    model, tokenizer = get_embedding_model()

    responses_1 = [f"{q['prompt']}\n\n{q['response_1']}" for q in valid_questions]
    responses_2 = [f"{q['prompt']}\n\n{q['response_2']}" for q in valid_questions]

    embeddings_1 = embed_texts(responses_1, model=model, tokenizer=tokenizer, show_progress=False)
    embeddings_2 = embed_texts(responses_2, model=model, tokenizer=tokenizer, show_progress=False)

    embeddings_1 = torch.tensor(embeddings_1, dtype=torch.float32)
    embeddings_2 = torch.tensor(embeddings_2, dtype=torch.float32)
    labels_tensor = torch.tensor(labels, dtype=torch.float32)

    # Train user vector
    print(f"\nTraining user vector for {century}...")
    w = train_user_vector(
        V=V,
        embeddings_1=embeddings_1,
        embeddings_2=embeddings_2,
        labels=labels_tensor,
        rank=rank,
        epochs=args.epochs,
        learning_rate=args.learning_rate,
        device=args.device,
    )

    # Save results
    user_id = f"historical_{century}"
    if pref_data.get('user_profile'):
        user_id += f"_{hash(pref_data['user_profile']) % 10000}"

    output_path = output_dir / f"W_{user_id}.pt"
    torch.save({
        'user_id': user_id,
        'century': century,
        'user_profile': pref_data.get('user_profile'),
        'w': w,
        'n_questions': len(valid_questions),
        'preferences_file': str(prefs_path),
    }, output_path)

    print(f"\nSaved user vector to {output_path}")

    print(f"\n{'='*60}")
    print("Training complete!")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
